### PR TITLE
Feature/code refactor

### PR DESCRIPTION
**Pull request by wgolledge**
- Removed unnecessary prototypes
- Added `getExceptionMsg` func
- Refactored for loops into reduce funcs for a more declarative over imperative style.

Please let me know what you think!

### CODE REVIEW

**Comment by bluet** [comment]
@wgolledge Thank you so much for the PR :+1: , and sorry for the late reply.

Autotest failed before due to unknown reason but it's passed now. :ok_hand: 

Those *unnecessary prototypes* and the for-loop were for backward compatibility due to API change and for easier debugging, but yup I agree they can be removed now. :100: 

:warning:  There are a few minor changes I might need your help to fix before merging, if you don't mind. :smiley_cat:

**Review by bluet — CHANGES_REQUESTED** [review]
some `'` became `"` which should stay in `'`. ex, *what **'** s*

**Comment by wgolledge** [comment]
I'll take a look now 😄

**Comment by wgolledge** [comment]
Hopefully that should now be fixed!

**Pull request merged**
